### ISSUE TITLE
Unable to run tests using openjdk16

### ISSUE THREAD

**Issue by billbsing** [Convex-Dev/convex#222]
The first init test fails.. with a parboiled InitializerError exception
```
[INFO] Running convex.core.init.InitTest
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.023 s <<< FAILURE! - in convex.core.init.InitTest
[ERROR] testHero  Time elapsed: 0.007 s  <<< ERROR!
java.lang.ExceptionInInitializerError
        at convex.core.init.InitTest.<clinit>(InitTest.java:24)
Caused by: java.lang.RuntimeException: Error creating extended parser class: Could not determine whether class 'convex.core.lang.Reader$$parboiled' has already been loaded
        at convex.core.init.InitTest.<clinit>(InitTest.java:24)
Caused by: java.lang.RuntimeException: Could not determine whether class 'convex.core.lang.Reader$$parboiled' has already been loaded
        at convex.core.init.InitTest.<clinit>(InitTest.java:24)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @4034c28c
        at convex.core.init.InitTest.<clinit>(InitTest.java:24)
```

nearly all subsequent tests also fail..

Even if I get to compile and package the java. when I run it I get
```
Jul 05, 2021 5:06:55 PM convex.cli.LocalStart run
INFO: Starting local network with 8 peer(s)
Jul 05, 2021 5:06:55 PM convex.cli.Main execute
SEVERE: null
```
so looks like parboild rewrite is a go

**Comment by mikera** [comment]
Possibly related issues other people have run into:
- https://github.com/immutables/immutables/issues/1283
- https://github.com/scala/community-build/issues/1354

**Comment by mikera** [comment]
I believe this is fixed with the replacement of Parboiled with ANTLR
