### ISSUE TITLE
Bad total amount when more than one genesis keys is used

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex#401]
Initializing a new state throws when there is more than one genesis key provided because the total funds are not equal to the max supply:

```
java.lang.Error: Bad total amount: 934900600000000000
        at convex.core.init.Init.createBaseState(Init.java:168)
        at convex.core.init.Init.createState(Init.java:205)
```

**Comment by helins** [comment]
Confirmed that this was faulty only because some keys were duplicated.
So a better error message will do 👍
