### ISSUE TITLE
CLI fails with a SLF4J exception

### ISSUE THREAD

**Issue by billbsing** [Convex-Dev/convex#424]
The CLI crashes on linux, and returns with an exception.

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/bill/Clients/Convex-Dev/convex/convex-cli/target/convex-cli.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Exception in thread "main" java.lang.ClassCastException: class org.slf4j.helpers.NOPLogger cannot be cast to class ch.qos.logback.classic.Logger (org.slf4j.helpers.NOPLogger and ch.qos.logback.classic.Logger are in unnamed module of loader 'app')
        at convex.cli.Main.mainExecute(Main.java:156)
        at convex.cli.Main.main(Main.java:132)

```
This is because the version of logback we are using is to old for SL4J
so..

To fix we need to upgrade `SLF4J` to 2.0.3 and `logback` to version 1.3.3

**Comment by mikera** [comment]
Looks good, thanks!
