### ISSUE TITLE
"Bad checksum" error when creating new account

### ISSUE THREAD

**Issue by oakes** [Convex-Dev/convex#427]
I'm seeing the following error when I try creating an account. This happens consistently, even when I recreate my keystore with new keys. I'm running on the `develop` branch.

```
sekao@Zachs-MacBook-Pro-2 convex % ./convex account create --public-key=5189a4ef9649b735b40e8708dffe6885772094ba9b5e65e89ef3959822bd9a12
19:47:44.126 [main] WARN convex.cli.Main - No password for keystore: defaulting to blank password
Error creating account
Underlying cause:
java.lang.Error: Cannot connect as a peer java.lang.IllegalArgumentException: Bad checksum at position 0 in address b7d991f864BC970e05BF3de8515C0A84081C70E93f9ff867fcd765E170b05096
	at convex.cli.Main.connectAsPeer(Main.java:419)
	at convex.cli.AccountCreate.run(AccountCreate.java:76)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at convex.cli.Main.mainExecute(Main.java:167)
	at convex.cli.Main.main(Main.java:132)
```

The stacktrace obscures where the real error is due to the try/catch in `connectAsPeer`. Here is where the error actually happens:

```
	at convex.core.data.AccountKey.fromChecksumHex(AccountKey.java:188)
	at convex.cli.peer.SessionItem.createFromString(SessionItem.java:51)
	at convex.cli.peer.Session.load(Session.java:32)
	at convex.cli.Helpers.getSessionItem(Helpers.java:89)
	at convex.cli.Main.connectAsPeer(Main.java:408)
	at convex.cli.AccountCreate.run(AccountCreate.java:76)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at convex.cli.Main.mainExecute(Main.java:167)
	at convex.cli.Main.main(Main.java:132)
```

**Comment by oakes** [comment]
If it helps, this is my `~/.convex/session.conf`

```
#Convex Session
#Sun Oct 30 19:47:27 EDT 2022
0=b7d991f864BC970e05BF3de8515C0A84081C70E93f9ff867fcd765E170b05096,localhost\:58689,/var/folders/2b/                              rgmrml2s3dl1600vnhnc85vc0000gn/T/convex-db-1644748780358998555.tmp
1=29A360a5967f2A191c228d0f15F6AA5E71035646C6feCFfa318f6b2b13Cc48E1,localhost\:58690,/var/folders/2b/                              rgmrml2s3dl1600vnhnc85vc0000gn/T/convex-db-1644748780358998555.tmp
2=5189a4eF9649b735b40E8708Dffe6885772094bA9b5e65e89eF3959822BD9A12,localhost\:58691,/var/folders/2b/                              rgmrml2s3dl1600vnhnc85vc0000gn/T/convex-db-1644748780358998555.tmp
```

**Comment by oakes** [comment]
I looked into it a bit and it appears that it's actually making a different (incorrect) hash for the checksum than the one made when the keys were first generated. I don't know exactly why yet, but it seems to be something related to the use of `ThreadLocal` to get the digest. If I replace it with a direct call to `MessageDigest.getInstance` it works without error:

```diff
diff --git a/convex-core/src/main/java/convex/core/crypto/Hashing.java b/convex-core/src/main/java/convex/core/crypto/Hashing.java
index 05abd52c..45d915f3 100644
--- a/convex-core/src/main/java/convex/core/crypto/Hashing.java
+++ b/convex-core/src/main/java/convex/core/crypto/Hashing.java
@@ -41,7 +41,11 @@ public class Hashing {
         * @return MessageDigest instance
         */
        public static MessageDigest getSHA3Digest() {
-               return sha3Store.get();
+               try {
+                       return MessageDigest.getInstance("SHA3-256");
+               } catch (NoSuchAlgorithmException e) {
+                       throw new Error("SHA3-256 algorithm not available", e);
+               }
        }
```

**Comment by mikera** [comment]
This looks like it is to do with the Checksum tests (intended to help fix typos in keys). Will take a look, thanks @oakes for the report!
